#%RAML 1.0 Trait
  usage: mantain transcation idn
  headers:
      x-transcation-id:
        type: string
        description: Transcation ID
        example: "wqe-ewqrwq-rqwrwqe-w-r"
        required: fasle